# name: codadash.com
# on:
#   push:
#     branches: [main]
# jobs:
#   deploy:
#     if: "! contains(github.event.commits[0].message, '[no ci]')"
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: SSH
#         if: ${{ github.ref == 'refs/heads/main' }}
#         uses: appleboy/ssh-action@master
#         env: 
#           PASS: ${{ secrets.PASSWORD }}
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.PASSWORD }}
#           envs: PASS
#           script: |
#             cd /home/codabool/codadash.com
#             git pull
#             echo "$PASS" | sudo -S systemctl restart codadash
